services:
  nextjs:
    build: .
    ports:
      - '3001:3000'
    platform: linux/amd64
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://209.38.188.191:3000
      - S3_ENDPOINT_URL=https://fra1.digitaloceanspaces.com
      - S3_BUCKET_NAME=lms-entrepreneurship-school-s3
      - S3_ACCESS_KEY_ID=DO00EZY6GGGNJBKDFZJ6
      - S3_SECRET_ACCESS_KEY=YD/GWaSkEAT891SjCUW8cB5KJZ8jG70MzQLeBJ/J7/8
      - DIGITALOCEAN_API_KEY=dop_v1_b25e9cdd380fc72eb32b410f23b7a9130522a7918bc44fda4ce24bd1355adb24